version: '3.8'
services:
  app:
    depends_on:
      - db
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - './server/src:/usr/src/app/src'
      - './server/package.json:/usr/src/app/package.json'
      - './server/tsconfig.json:/usr/src/app/tsconfig.json'
    environment:
      - DB_URL=postgres://admin:mypassword@db:5432/dev_db
      - CLIENT_ID=
      - CLIENT_SECRET=
      - FRONTEND_URL=http://localhost:8081
      - REDIRECT_URI=http://localhost:3000/callback
      - JWT_SECRET=secret
      - APP_USER_ADMIN=admin
      - APP_USER_PASSPHRASE=admin
    networks:
      - backend

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: dev_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  worker:
    depends_on:
      - app
      - db
    build:
      context: ./worker
      dockerfile: Dockerfile
    environment:
      - DB_URL=postgres://admin:mypassword@db:5432/dev_db
      - CLIENT_ID=
      - CLIENT_SECRET=
    volumes:
      - ./worker:/usr/src/app
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  pgdata:
